// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ToZNM45bbqo_IG6ePmLr_XgtxRdKTIo',
    appId: '1:895715615414:web:f54f8617cc303dbc963c17',
    messagingSenderId: '895715615414',
    projectId: 'socialmedi',
    authDomain: 'socialmedi.firebaseapp.com',
    storageBucket: 'socialmedi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFpefmM4A4MxfKuxcdhvZnLGyza7WywHA',
    appId: '1:895715615414:android:6b67dad7383a07ff963c17',
    messagingSenderId: '895715615414',
    projectId: 'socialmedi',
    storageBucket: 'socialmedi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFRlt90hJ5LjuL6X7A3rM1cyCGs6xvszQ',
    appId: '1:895715615414:ios:5856d6d81eea45eb963c17',
    messagingSenderId: '895715615414',
    projectId: 'socialmedi',
    storageBucket: 'socialmedi.firebasestorage.app',
    iosBundleId: 'com.example.socialmedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFRlt90hJ5LjuL6X7A3rM1cyCGs6xvszQ',
    appId: '1:895715615414:ios:5856d6d81eea45eb963c17',
    messagingSenderId: '895715615414',
    projectId: 'socialmedi',
    storageBucket: 'socialmedi.firebasestorage.app',
    iosBundleId: 'com.example.socialmedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8ToZNM45bbqo_IG6ePmLr_XgtxRdKTIo',
    appId: '1:895715615414:web:f6106a53cdcc500d963c17',
    messagingSenderId: '895715615414',
    projectId: 'socialmedi',
    authDomain: 'socialmedi.firebaseapp.com',
    storageBucket: 'socialmedi.firebasestorage.app',
  );
}
